// <auto-generated />
using FVCPD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FVCPD.Data.Migrations
{
    [DbContext(typeof(FVCPDbContext))]
    [Migration("20220226185754_Added Conjugated Verb")]
    partial class AddedConjugatedVerb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("FVCPD.Data.Models.ConjugatedVerb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conjugation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mood_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pronound_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tense_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Verb_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Pronound_Id", "Tense_Id", "Mood_Id", "Verb_Id" }, "UK_ConjugatedVerb")
                        .IsUnique();

                    b.ToTable("ConjugatedVerbs");
                });

            modelBuilder.Entity("FVCPD.Data.Models.Mood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UK_Mood_Name")
                        .IsUnique();

                    b.ToTable("Moods");
                });

            modelBuilder.Entity("FVCPD.Data.Models.Pronoun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UK_Pronoun_Name")
                        .IsUnique();

                    b.ToTable("Pronouns");
                });

            modelBuilder.Entity("FVCPD.Data.Models.Tense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UK_Tense_Name")
                        .IsUnique();

                    b.ToTable("Tenses");
                });

            modelBuilder.Entity("FVCPD.Data.Models.Verb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Infinitive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PastParticiple")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Infinitive" }, "UK_Verb_Infinitive")
                        .IsUnique();

                    b.ToTable("Verbs");
                });
#pragma warning restore 612, 618
        }
    }
}
